### ISSUE TITLE
[not an issue] Config QuakeVR to use real life movement instead of controller

### ISSUE THREAD

**Issue by bronymusician** [DrBeef/QuakeQuest#25]
Is there any kind of movement multiplier to do this? All options seem to affect only the controllers

Thanks!

**Comment by DrBeef** [comment]
Not sure I understand what it is you are asking for..

**Comment by bronymusician** [comment]
Sorry for the delay!
Is ir possible to play QuakeQuest on a huge field without using the controllers for movement? 

I try but it moves so little

**Comment by neitey** [comment]
I played Quake arena style and it works. One unit in Quake translates to one distance unit in real life pretty accurate. But the rooms and buildings are just so huge, that you think you are not moving fast.

**Comment by clayg** [comment]
QuakeQuest was the first VR experience I spent much time with that used the controller stick for movement.  In my limited experience with VR, moving with a controller felt unnatural and made me uncomfortable (and I've played mouse/keyboard FPS for ... well at least 24 years :grin: )

Meanwhile, I had no idea the competitive PvP area shooter scene had pushed "bunny hopping" to such an [extreme](https://www.youtube.com/watch?v=rTsXO6Zicls).

Does anyone know what might be required to trigger an action like Jump when the headset moves above a (configurable?) height threshold instead of just pressing A?  Basically the opposite of [crouch detection](https://forums.oculusvr.com/developer/discussion/74414/how-do-you-set-up-crouch-detection).
