### ISSUE TITLE
Undesired movement

### ISSUE THREAD

**Issue by animemoko** [DrBeef/QuakeQuest#3]
As I wave around my right controller the character walks around, I couldn't find how to turn this off

**Comment by BrainSlugs83** [comment]
Per the readme's `Known Issues` section:
>Some slight movement when moving weapon around (this is due to how I had to implement 6DoF) however you won't notice this in the heat of battle, only when you stand still marveling at the true 6DoF weapon in your hand.

>I couldn't find how to turn this off

Fix the bug and submit a pull request?

**Comment by animemoko** [comment]
U right it was on 'readme' sorry

**Comment by DrBeef** [comment]
This one would be pretty much impossible to fix I'm afraid, though everyone is welcome to try. Here's why:

Quake's player movement is actually implemented by the client sending the player's velocities (sideways, forwards/backwards) to the server, the server then calculates where the player will be next frame and sends that back to the client for next frame rendering.
The problem is it means positional movement is not simply a case of saying "I am now here".. but rather figuring out some values of velocities that should move the player in such a way it matches up with his/her real world movement!
To make things even more complicated, to make the game 6DoF, I treat the weapon (dominant hand controller) as the player and do the above movement processing with that controller's position.. and then I translate the camera back again based on where the HMD is relative to the dominant hand controller! That's why if you get really close to a wall you can occasionally clip through it. It's also why moving the gun about doesn't leave you exactly where you started as the numbers I came up with are best estimates.. they could be improved upon, but I doubt it would be possible to get them perfect.

**Comment by animemoko** [comment]
Maybe setting left hand as dominant in that matter would reduce the effect, I barely move left controller around while playing but right one I do, since it's meant for aiming.

**Comment by DrBeef** [comment]
I'm not sure you understood the problem, I didn't arbitrarily pick the right controller to dictate the position. 

The engine originates weapon projectiles from the location of what it understands to be the player. The player and his/her location has to therefore be the dominant hand controller holding the weapon, the one you shoot from. If I were to just draw the weapon where the dominant controller is, but the engine thinks the location of the off-hand controller is the player location, then that is where projectiles originate from and it would look really terrible.

It is a fundamental constraint of the engine unfortunately.

**Comment by animemoko** [comment]
Now I get it, yeah seems complicated. Yet I recall to be playing this game for rift and that didn't happen so there must be a way.

Anywas this is not big deal! Totally playable as it is

**Comment by BenMcLean** [comment]
You either have to give up on the assumption that you hold your gun in your hand and projectiles come out of it, or you have to give up on the assumption that player movement shouldn't happen when you move your gun. Those two assumptions cannot both be implemented in the Quake engine at the same time.

**Comment by Protowalker** [comment]
Could you edit the DarkPlaces code to always render from the headset position?

**Comment by Protowalker** [comment]
If I understand correctly, the value that the server returns isn't precise enough to always calculate the exact offset from the headset to the gun's position in the world. If you could somehow extrapolate the guns position to a more accurate degree, would this problem go away? @DrBeef
