### ISSUE TITLE
Audio Delay

### ISSUE THREAD

**Issue by FolkSong** [DrBeef/QuakeQuest#37]
There is a substantial delay between firing the gun and hearing the sound, I'd say maybe 1/4 second. It's present in Quake2Quest as well. It's unfortunate because it takes away from the visceral nature of the shooting. I'm pretty sure all sounds are delayed, gunshots are just the most obvious. I'm using a Quest 1 if it matters.

**Comment by fighterguard** [comment]
> I'm pretty sure all sounds are delayed, gunshots are just the most obvious. I'm using a Quest 1 if it matters.

@FolkSong You're absolutely right. There is a huge audio delay across the board. It's not just the gunshots. And it also happens in the Quest 2, so it's not a performance issue. And it IS very annoying and distracting.
I'm not gonna promise anything, but I'm gonna clone the repo and try and find a way to fix that and other annoyances with this port, including attaching the HUD to the off-hand for better visibility, the ability to change the scale of said HUD, and maybe a weapons wheel for quick selection like in the recent remaster by Nightdive, or perhaps the possibility to equip weapons from the arm-mounted HUD, just like in ViveCraft.

I know I'm being very ambitious. I've never done any development on id Tech 1, or on Oculus, but I am a professional developer, which is why I want to attempt this. Just don't hold your breath. I may not achieve anything, but I do want to try, and maybe work on my own VR ports in the future.

**Comment by FolkSong** [comment]
Ok, best of luck! I think someone on reddit said the delay was already present in the original non-VR Android port from Beloko games, which this was ported from.

Your other ideas sound great too!

**Comment by DrBeef** [comment]
I've merged in the OpenSLES implementation from Beloko's build and it works and the audio lag is gone. I'll release this properly very soon, but if you want to try it in the meantime you can download the build here:

https://drive.google.com/file/d/14bsgPrvSNemUy3_pAtHgxnznodEN6_rv/view?usp=sharing

There are a number of other changes in this build:

* Two handed weapons
* Weapon Haptics
* Additional right-hand keys on the rubbish virtual keyboard for function keys
* Much clearer menu screens using layers 
* 120hz unlocked (use command line parameter: -r 120)

**Comment by FolkSong** [comment]
Thanks so much Simon! I'll try it soon.

Edit: tried the release version and it's great!
